baseURL: "https://jaylife.cc"
title: 失控谜语
paginate: 5
theme: PaperMod
hasCJKLanguage: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-ZX7WJVMVK2

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: 失控谜语
  description: "NAS、OpenWrt和Home Assistant相关内容，分享科技产品、有趣软件和折腾教程"
  keywords: [NS, OpenWrt, Home Assistant]
  author: Jay
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/images/favicon.ico"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /images/logo.png
    iconHeight: 26

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: "失控谜语"
    subtitle: "分享科技产品、有趣软件和折腾教程"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "失控谜语"
    Content: "Hi,there! 欢迎来到失控谜语栖息地


    我会在这里分享一些科技产品、有趣的软件和小白教程


    如果你对**NAS**、**OpenWrt**和**Home Assistant**感兴趣，欢迎关注"

  socialIcons:
    - name: twitter
      url: "https://twitter.com/jayziven"
    - name: instagram
      url: "https://www.instagram.com/jayziven"
    - name: github
      url: "https://github.com/socekin"
    - name: telegram
      url: "https://t.me/jayzlife"

  analytics:
    google:
      SiteVerificationTag: "G-ZX7WJVMVK2"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page

  #editPost:
    #URL: "https://github.com/<path_to_repo>/content"
    #Text: "Suggest Changes" # edit text
    #appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 5
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20

#    - identifier: example
#      name: example.org
#      url: https://example.org
#      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
